name: Test

on:
    push:
        paths:
            - 'docs/**'
            - '.github/workflows/test.yml'
            - 'src/**'
            - 'tests/**'
        branches:
            - main

jobs:
    tests:
        name: Test using tox 🔎
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12", "3.13"]

        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                  enable-cache: true
                  cache-dependency-glob: "uv.lock"

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install tox
              run: uv run --dev tox

            - name: Run tests with tox for Python ${{ matrix.python-version }}
              run: tox